{% set name = "napari-error-reporter" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_error_reporter-{{ version }}.tar.gz
  sha256: 7c499f526570762630daa1c87d863ecc5265621765c5b6e3f0bdbc271e774d53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - appdirs
    - python >=3.8
    - qtpy
    - sentry-sdk

test:
  imports:
    - napari_error_reporter
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/napari-error-reporter
  summary: Opt-in automated bug/error reporting for napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tlambert03
